import './globals.css'
// import { Poppins } from 'next/font/google'
import Navbar from './components/Navbar'
import { authOptions } from './api/auth/[...nextauth]/route'
import { getServerSession } from 'next-auth'
// import AuthProvider from './AuthProvider'


// const poppins = Poppins({ subsets: ['latin','latin-regular'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//when we work with server components we can make async 
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //Fetch User
  const session=await getServerSession(authOptions)
  console.log(session);
  
  return (
    // <AuthProvider>
    <html lang="en">
      <body className='mx-10'>
      <div>
      <Navbar user={session?.user} expires={session?.expires!} />
        {children}
      </div>
        </body>
    </html>
    // </AuthProvider>
  )
}
